import pygtk
pygtk.require('2.0')
import gtk

# import webkit

WINDOW_WIDTH = 1024
WINDOW_HEIGHT = 600
WINDOW_BORDER_WIDTH = 10
WINDOW_TITLE = "BaseStation"

JOYSTICK_ID = 0

NUM_BUTTON_EVENTS = 3
STOP_CONTROLLER_EVENT = 0
VID_STREAM_EVENT = 1
VID_STOP_EVENT = 2
