import pygtk
pygtk.require('2.0')
import gtk

# import webkit

WINDOW_WIDTH = 1024
WINDOW_HEIGHT = 600
WINDOW_BORDER_WIDTH = 10
WINDOW_TITLE = "BaseStation"

ROBOTICSBASE_NUM_EVENTS = 2
ROBOTICSBASE_STOP_LISTENER = 0
ROBOTICSBASE_STREAM_VIDEO = 1

CONTROLLER_SLEEP_INTERVAL = 0.25
